[build]
  command = "npm run build"
  publish = "dist"
  
[context.production]
  environment = { NODE_VERSION = "20.11.1" }

[[redirects]]
  from = "https://ascensorimonza.com/*"
  to = "https://www.lombardaascensori.it/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ascensorimonza.com/*"
  to = "https://www.lombardaascensori.it/:splat"
  status = 301
  force = true